name: Setup OSS CAD Suite
description: Set up a specific version of OSS CAD Suite and add the command-line tools to the PATH
author: GitHub
branding:
  color: purple
  icon: code
inputs:
  osscadsuite-version:
    description: Version range or exact version of OSS CAD Suite to use
runs:
  using: node12
  main: dist/index.js
