name: Setup OSS CAD Suite
description: This downloads and sets up a pre-build EDA environment from the YosysHQ OSS CAD Suite, allowing you to have all the most up-to-date tools available to you.
author: YosysHQ
branding:
  color: purple
  icon: cpu
inputs:
  version:
    description: Version range or exact version of OSS CAD Suite to use
  python-override:
    description: Use Python3 provided with OSS CAD Suite
    default: false
runs:
  using: node16
  main: dist/index.js
