name: 'Test Action'
on:
  push:
    branches:
      - 'main'
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - name: Tool Versions
        shell: bash
        run: |
          yosys --version
          sby --help | head -1
          nextpnr-ice40 --version
          nextpnr-ecp5 --version
          nextpnr-nexus --version
          verilator --version
          yices --version | head -1

          sby --help | head -1
          yices --version | head -1
